create database assesment;

use assesment;

-- Que-1
SELECT * FROM WORKER_TABLE ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

-- QUE-2
SELECT * FROM WORKER_TABLE WHERE FIRST_NAME IN ('VIPUL', 'SATISH');

-- QUE-3
SELECT * FROM WORKER_TABLE WHERE FIRST_NAME LIKE '_____h'; 

-- QUE-4
SELECT * FROM WORKER_TABLE WHERE SALARY BETWEEN 1 AND 100000;

-- QUE-5
SELECT  DEPARTMENT, COUNT(*) AS DUPLICATEE FROM WORKER_TABLE
GROUP BY  DEPARTMENT HAVING COUNT(*) > 1;

-- QUE-6
SELECT * FROM WORKER_TABLE LIMIT 6;

-- QUE-7
SELECT DEPARTMENT, COUNT(*) AS EMP_COUNT FROM WORKER_TABLE
GROUP BY DEPARTMENT
HAVING COUNT(*) < 5;

-- QUE-8
SELECT DEPARTMENT, COUNT(*) AS EMP_COUNT FROM WORKER_TABLE
GROUP BY DEPARTMENT;

-- QUE -9
SELECT FIRST_NAME, DEPARTMENT, SALARY FROM WORKER_TABLE
WHERE (DEPARTMENT, SALARY) IN 
(
    SELECT DEPARTMENT, MAX(SALARY)
    FROM WORKER_TABLE
    GROUP BY DEPARTMENT
);

-- -----------------------------------que2-----------------------------------

-- QUE-1
SELECT * FROM student;

-- QUE-2
SELECT StdName, DOB FROM student ; 

-- QUE-3
SELECT * FROM student WHERE percentage >= 80; 

-- QUE-4
SELECT StdName, Streamm, Percentage from student WHERE percentage > 80; 

-- QUE-5
SELECT * FROM student WHERE streamm = 'Science' AND percentage > 75; 





